service: culqi-test

useDotenv: true

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    API_URL: ${env:API_URL}
    POSTGRESQL_HOST: ${env:POSTGRESQL_HOST}
    POSTGRESQL_PORT: ${env:POSTGRESQL_PORT}
    POSTGRESQL_USERNAME: ${env:POSTGRESQL_USERNAME}
    POSTGRESQL_PASSWORD: ${env:POSTGRESQL_PASSWORD}
    POSTGRESQL_DATABASE: ${env:POSTGRESQL_DATABASE}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PORT: ${env:REDIS_PORT}
    REDIS_USER: ${env:REDIS_USER}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    REDIS_DB: ${env:REDIS_DB}
    CRYPTO_KEY: ${env:CRYPTO_KEY}
    CRYPTO_IV: ${env:CRYPTO_IV}

functions:
  createToken:
    handler: src/handlers/tokens.create
    events:
      - http:
          path: /tokens
          method: post

  getCard:
    handler: src/handlers/cards.get
    events:
      - http:
          path: /cards
          method: get
